### ISSUE TITLE
Hosting ursina 

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [kstzl/UrsinaNetworking#4]
Sir I was making my own game that I don't want to disclose but I tried the minecraft clone from ursina GitHub page but I don't know how to broadcast the ongoing game on the server nor the client side.
So if you could give a step by step solution or you could share your YouTube minecraft multiplayer player game code. Then I would get an example and it would be easier for me.
Thank you

**Comment by kstzl** [comment]
Hello, sorry for the late.
Check out this example : https://github.com/kstzl/UrsinaNetworking/tree/main/ursinanetworking/examples/replicated
It use something called "Replicated" and server / client sides.
Gl ! :)

**Comment by Shuvadip-Ghosh** [comment]
Thank you sir I understood how to do it thanks sir very much.
