### ISSUE TITLE
why onConnection**Etablished**?

### ISSUE THREAD

**Issue by xzripper** [kstzl/UrsinaNetworking#6]
why onConnection**Etablished**?
Maybe onConnection**Established**?

**Comment by Lunar-Void** [comment]
Has this been switched out yet?

**Comment by xzripper** [comment]
no

**Comment by kstzl** [comment]
Sorry for the late guys ! Merged ! @Lunar-Void @xzripper @zai1208

**Comment by xzripper** [comment]
Thank!
